# Generated by Django 3.2.16 on 2023-01-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20230107_1529'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Не доступна'), ('o', 'Взять на руки'), ('a', 'Свободный'), ('r', 'Занято')], default='m', help_text='Забронировать книгу', max_length=1),
        ),
    ]
